### ISSUE TITLE
How to read / view the DB with all my Pinboard bookmarks?

### ISSUE THREAD

**Issue by sfd99** [onozaty/browser-online-bookmark-incsearch#11]
**Hi Onozaty -**

INCsearch 
_continues_ to be **wonderful**!.
(I have the latest version, under Ubuntu LINUX).

**Question:**

As you kindly wrote to me before,
I found the DB 
with all my Pinboard bookmarks,
as DL by INCsearch.

The files in my Ubuntu Linux 20.04 PC 
are in my local HD path:

**~/.config/google-chrome/Local Extension Settings/lpaleambpedcnbeaolhoandbffjgidao** 

In the above folder,
there is a _large_ file called:

  **000003.ldb**   (with 15.8MB).

That _must be_ the INCsearch database 
with all my Pinborad bookmarks!.

Great.
But how do I read this file 
with an 
**.ldb** extension?

I can not open it 
or read it...

I need to save it / export this bookmarks file
as a **CSV**, **JSON** or **HTML** file...

_Help!_
**SFd99
latest version of INCsearch
Ubuntu Linux 20.04 PC**

**Comment by onozaty** [comment]
Hi @sfd99 

Can you please try the following from the DevTools Console.

```javascript
bookmakrs = await Storage.get('bookmarks');
downloadLink = document.createElement('a');
downloadLink.download = 'bookmarks.json';
downloadLink.href = URL.createObjectURL(new Blob([JSON.stringify(bookmakrs, null, 2)], { 'type' : 'text/plain' }));
downloadLink.setAttribute('hidden', true);
document.body.appendChild(downloadLink);
downloadLink.click();
downloadLink.remove();
```

This will download the JSON file.

Thanks.

**Comment by sfd99** [comment]
**Hi Onozaty,**

Thanks for that quick response!.

How and where do I enter your code
in my **Chromium browser**? 
- it's Version 101.0.4951.54 
under **Ubuntu Linux 20.04**.

What are the steps do do that?.

Sorry, 
I'm not that deeply systems-oriented... :-)

Thanks for your patience with me!.
**SFd99**

**Comment by onozaty** [comment]
With this extension page open, press Ctrl+Shift+J to open DevTools.

![image](https://user-images.githubusercontent.com/47337/167321317-7de4a66e-0a54-427a-87cb-9018798a0a92.png)

The following may be helpful on how to open DevTools in Chrome.

* https://linuxhint.com/chrome-dev-tools/

Thanks

**Comment by sfd99** [comment]
_Ah!_ 
I had done **Ctrl-Shift-J**,
but not opened yet the **INCsearch** extension.

With your clear and precise
instructions
it now **worked** like magic!.

Thank you so much, Onozaty.
Domo * 10^6 !!.

Have a nice, peaceful week,
Best, 

**sfd99
San Francisco**
