### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by ecogit** [onozaty/browser-online-bookmark-incsearch#12]
Thanks to the regex-inspired searching ability of [Online Bookmark Incremental Search](https://github.com/onozaty/browser-online-bookmark-incsearch) to entering multiple keywords and apply the operators AND("keyword-a keyword-b"), OR("keyword-a|keyword-b") and NOT("!keyword"), is it the faster tool to query full-text descriptions of bookmarks when compared with tools to create & manage those (e.g. with the fabulous [Pinboard Plus](https://chrome.google.com/webstore/detail/pinboard-plus/mphdppdgoagghpmmhodmfajjlloijnbd) on Chromium, [Pinboard Pin](https://addons.mozilla.org/en-US/firefox/addon/pinboard-pin/) on Firefox and [Pinkt](https://play.google.com/store/apps/details?id=com.fibelatti.pinboard&hl=en&gl=US) on Android.

Therefore, for many power users IncSearch could become a valuable daily companion in their information management workflow.

While many of us aren't programmers, thus can't help you preparing pull-requests for bug-fixing and additional functionality, we'd still like to show gratitude for your tremendous long-standing efforts and also encourage further development. Have you got a profile on a recurrent donations platform such as [Liberapay](url), a PayPal account, IBAN or other means to receive financial support?

**Comment by onozaty** [comment]
Hi @ecogit 

Thank you very much. I am very happy to hear you say so.
You can make a donation below.

* https://github.com/sponsors/onozaty

Thanks.

**Comment by ecogit** [comment]
You are welcome @onozaty (and @dandv), thank you for the great work! 

I just remitted via GitHub Sponsors. Cheers 🍻
