### ISSUE TITLE
Bookmarks loading is failed. (200:OK)

### ISSUE THREAD

**Issue by ecogit** [onozaty/browser-online-bookmark-incsearch#13]
Hi IncSearch Team,
After years of perfectly functioning, since a few months my bookmarks don't load anymore. 

Error message:
    
    Bookmarks loading is failed. (200:OK)

Screenshot:    
![image](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/9ea62df8-3705-4da6-89a9-2a4aaeacad54)

Configuration:
- ~10'500 Pinboard bookmarks (*.json backup file ~10.3 MB)
- Re-installed Add-on repeatedly
- Firefox, Brave and Chromium
- Ubuntu Linux 23.04 and Windows 11

Any idea what the problem could be?

Suspicion:
It stopped working on all devices around the same period, namely when my Pinboard account grew beyond 10.0 MB.

**Comment by onozaty** [comment]
Hi @ecogit 

I have not had any problems with my pinboard account.

It may be due to data size.
Could you please check your browser's developer tools for any errors when this error occurs?

Thanks.

**Comment by onozaty** [comment]
Also, try the following URL to see what you see.

* https://api.pinboard.in/v1/posts/all

It should originally display XML.

**Comment by ecogit** [comment]
Thank you for your helpful advise @onozaty ! Thanks to that I could locate and solve the issue :-)

In around 6 bookmarks from years ago there where a few (very) special symbols like the following which caused the XML parsing blockage: 

        (music note)
     ▷   (triangle black right-pointing)
        (yarn node)
        (tick sign) 

Once I removed those everything worked well again.

- - -  

**XML parsing issue:**
![Pinboard_Eocas_IncSearch_Browser-inspector_Errors_XML-2_EG](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/24e3d697-0290-4909-9593-136a32d9987b)

![Pinboard_Eocas_IncSearch_Browser-inspector_Errors_XML-1_EG](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/827be4d1-9ace-4bce-aae3-d52b952d277a)


**Console output:**
![Pinboard_Eocas_IncSearch_Browser-inspector_Errors](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/4f76d7ec-f418-4e43-bd0c-c1553844dad8)   ([source](https://pinboard.in/u:eocas/b:34e270d50236))

**Comment by ecogit** [comment]
Thank you for your helpful advise @onozaty ! Thanks to that I could locate and solve the issue :-)

In around 6 bookmarks from years ago there where a few (very) special symbols like the following which caused the XML parsing blockage: 

        (music note)
     ▷   (triangle black right-pointing)
        (yarn node)
        (tick sign) 

Once I removed those everything worked well again.

- - -  

**XML parsing issue:**
![Pinboard_Eocas_IncSearch_Browser-inspector_Errors_XML-2_EG](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/24e3d697-0290-4909-9593-136a32d9987b)

![Pinboard_Eocas_IncSearch_Browser-inspector_Errors_XML-1_EG](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/827be4d1-9ace-4bce-aae3-d52b952d277a)


**Console output:**
![Pinboard_Eocas_IncSearch_Browser-inspector_Errors](https://github.com/onozaty/browser-online-bookmark-incsearch/assets/706228/4f76d7ec-f418-4e43-bd0c-c1553844dad8)   ([source](https://pinboard.in/u:eocas/b:34e270d50236))
